import { MenuItem, Review, Stat } from './types';
import { getAssetUrl } from './lib/images';

// Helper to bridge old usage to new utility if needed, but we'll update all calls
const getImageUrl = (name: string) => getAssetUrl(name);

export const MENU_ITEMS: MenuItem[] = [
  // INDIAN DISHES
  {
    id: 'in-1',
    name: 'Old Delhi Butter Chicken',
    description: 'Charcoal-grilled chicken in a rich, creamy tomato gravy with a hint of dried fenugreek and butter.',
    price: 28,
    category: 'main',
    image: getImageUrl('butter_chicken'),
    rating: 4.9,
    tags: ['Non-Veg', 'Indian', 'Classic'],
  },
  {
    id: 'in-2',
    name: 'Paneer Tikka Platter',
    description: 'Cubes of fresh cottage cheese marinated in yogurt and spices, roasted in a clay oven with bell peppers.',
    price: 22,
    category: 'starters',
    image: getImageUrl('paneer_tikka'),
    rating: 4.8,
    tags: ['Veg', 'Indian', 'Spicy'],
  },
  {
    id: 'in-3',
    name: 'Royal Hyderabadi Biryani',
    description: 'Aromatic long-grain basmati rice cooked with tender lamb, saffron, and over 20 secret spices.',
    price: 34,
    category: 'main',
    image: getImageUrl('biryani'),
    rating: 5.0,
    tags: ['Non-Veg', 'Indian', 'Chef Special'],
  },
  {
    id: 'in-4',
    name: 'Masala Dosa',
    description: 'Crispy rice crepe filled with tempered potato mash, served with coconut chutney and tangy sambar.',
    price: 18,
    category: 'starters',
    image: getImageUrl('dosa'),
    rating: 4.7,
    tags: ['Veg', 'Indian', 'Healthy'],
  },
  {
    id: 'in-5',
    name: 'Kashmiri Rogan Josh',
    description: 'Slow-cooked lamb in a thin red gravy seasoned with ginger and dried Kashmiri chilies.',
    price: 32,
    category: 'main',
    image: getImageUrl('rogan_josh'),
    rating: 4.8,
    tags: ['Non-Veg', 'Indian', 'Spicy'],
  },

  // INTERNATIONAL DISHES
  {
    id: 'int-1',
    name: 'Margherita Pizza',
    description: 'San Marzano tomatoes, fresh buffalo mozzarella, basil, and aromatic extra virgin olive oil.',
    price: 24,
    category: 'main',
    image: getImageUrl('margherita_pizza'),
    rating: 4.9,
    tags: ['Veg', 'Italian', 'Classic'],
  },
  {
    id: 'int-2',
    name: 'Sushi Deluxe Platter',
    description: 'Selection of Nigiri, Sashimi, and Maki rolls featuring Bluefin tuna and fresh Scottish salmon.',
    price: 55,
    category: 'starters',
    image: getImageUrl('sushi'),
    rating: 5.0,
    tags: ['Non-Veg', 'Japanese', 'Seafood'],
  },
  {
    id: 'int-3',
    name: 'Chicken Ramen Bowl',
    description: '18-hour chicken bone broth, thin straight noodles, grilled chashu chicken, and ajitama egg.',
    price: 26,
    category: 'main',
    image: getImageUrl('ramen'),
    rating: 4.8,
    tags: ['Non-Veg', 'Japanese', 'Comfort'],
  },
  {
    id: 'int-4',
    name: 'Classic Beef Burger',
    description: 'Prime beef patty, aged cheddar, lettuce, tomato, and house-made burger sauce on brioche.',
    price: 22,
    category: 'main',
    image: getImageUrl('burger'),
    rating: 4.9,
    tags: ['Non-Veg', 'American', 'Classic'],
  },
  {
    id: 'int-5',
    name: 'Fettuccine Alfredo',
    description: 'Velvety Parmigiano-Reggiano sauce over fresh house-made fettuccine ribbons.',
    price: 25,
    category: 'main',
    image: getImageUrl('pasta_alfredo'),
    rating: 4.7,
    tags: ['Veg', 'Italian', 'Creamy'],
  },
  {
    id: 'int-6',
    name: 'Mexican Tacos',
    description: 'Three corn tortillas with spicy beef, cilantro, onion, and fresh lime salsa.',
    price: 18,
    category: 'starters',
    image: getImageUrl('tacos'),
    rating: 4.8,
    tags: ['Non-Veg', 'Mexican', 'Spicy'],
  },
  {
    id: 'int-7',
    name: 'Shrimp Pad Thai',
    description: 'Stir-fried rice noodles with jumbo shrimp, bean sprouts, tamarind sauce, and crushed peanuts.',
    price: 24,
    category: 'main',
    image: getImageUrl('pad_thai'),
    rating: 4.7,
    tags: ['Non-Veg', 'Thai', 'Classic'],
  },
  {
    id: 'int-8',
    name: 'Croissant Sandwich',
    description: 'Buttery flaky croissant with smoked turkey, swiss cheese, and honey mustard.',
    price: 18,
    category: 'starters',
    image: getImageUrl('croissant'),
    rating: 4.6,
    tags: ['Non-Veg', 'French', 'Light'],
  },
  {
    id: 'int-9',
    name: 'Lasagna',
    description: 'Layers of fresh pasta, slow-cooked beef ragu, creamy bechamel, and melted mozzarella.',
    price: 30,
    category: 'main',
    image: getImageUrl('lasagna'),
    rating: 4.9,
    tags: ['Non-Veg', 'Italian', 'Hearty'],
  },
  {
    id: 'int-10',
    name: 'Greek Salad',
    description: 'Heirloom tomatoes, cucumber, Kalamata olives, and a premium block of Greek feta cheese.',
    price: 19,
    category: 'starters',
    image: getImageUrl('greek_salad'),
    rating: 4.8,
    tags: ['Veg', 'Greek', 'Fresh'],
  },

  // DESSERTS
  {
    id: 'd-1',
    name: 'Chocolate Lava Cake',
    description: 'Warm, gooey dark chocolate center served with Madagascar vanilla bean gelato.',
    price: 18,
    category: 'desserts',
    image: getImageUrl('lava_cake'),
    rating: 4.9,
    tags: ['Veg', 'Decadent', 'Sweet'],
  },
  {
    id: 'd-2',
    name: 'Blueberry Cheesecake',
    description: 'New York style cheesecake topped with a compote of freshly picked wild blueberries.',
    price: 16,
    category: 'desserts',
    image: getImageUrl('cheesecake'),
    rating: 4.8,
    tags: ['Veg', 'Classic', 'Sweet'],
  },
  {
    id: 'd-3',
    name: 'Gulab Jamun',
    description: 'Golden fried milk dumplings in saffron syrup with silver vark and crushed pistachios.',
    price: 12,
    category: 'desserts',
    image: getImageUrl('gulab_jamun'),
    rating: 5.0,
    tags: ['Veg', 'Indian', 'Hot'],
  },
  {
    id: 'd-4',
    name: 'Belgian Waffles',
    description: 'Authentic Liège waffles with pearl sugar, fresh berries, and maple infusion.',
    price: 15,
    category: 'desserts',
    image: getImageUrl('waffles'),
    rating: 4.7,
    tags: ['Veg', 'Breakfast', 'Sweet'],
  },
  {
    id: 'd-5',
    name: 'Tiramisu',
    description: 'Espresso-soaked ladyfingers with whipped mascarpone cream and premium cocoa dusting.',
    price: 17,
    category: 'desserts',
    image: getImageUrl('tiramisu'),
    rating: 4.9,
    tags: ['Veg', 'Italian', 'Coffee'],
  },

  // BEVERAGES
  {
    id: 'b-1',
    name: 'Hibiscus Iced Tea',
    description: 'Craft brewed hibiscus petals with fresh mint and a touch of honey.',
    price: 9,
    category: 'beverages',
    image: getImageUrl('iced_tea'),
    rating: 4.7,
    tags: ['Veg', 'Healthy', 'Cold'],
  }
];

export const REVIEWS: Review[] = [
  {
    id: '1',
    name: 'Julianne Moore',
    avatar: 'https://i.pravatar.cc/150?u=julianne',
    rating: 5,
    comment: 'The ambiance is unmatched. Every bite felt like a journey through flavor landscapes.',
    role: 'Food Critic',
  },
  {
    id: '2',
    name: 'Marcus Chen',
    avatar: 'https://i.pravatar.cc/150?u=marcus',
    rating: 5,
    comment: 'Lumière Dining is the pinnacle of modern luxury. The 3D presentation of dishes is revolutionary.',
    role: 'Gourmet Enthusiast',
  },
  {
    id: '3',
    name: 'Sofia Rodriguez',
    avatar: 'https://i.pravatar.cc/150?u=sofia',
    rating: 5,
    comment: 'Hands down the best Wagyu I have had outside of Japan. Impeccable service.',
    role: 'Travel Blogger',
  }
];

export const STATS: Stat[] = [
  { label: 'Michelin Stars', value: '2' },
  { label: 'Wine Labels', value: '500+' },
  { label: 'Happy Guests', value: '50k+' },
  { label: 'Years of Excellence', value: '15' }
];

export const GALLERY_IMAGES = [
  getImageUrl('interior_1'),
  getImageUrl('interior_2'),
  getImageUrl('exterior'),
  getImageUrl('table_setting'),
  getImageUrl('cocktail_prep'),
  getImageUrl('chef_plating'),
];
